<% socket = `mysql_config --socket`.rstrip %>

development: &development
  adapter: mysql2
  username: root
  password:
  socket: <%= socket %>
  database: murdersnake_sample_client_development

test:
  database: murdersnake_sample_client_test
  <<: *development

production:
  database: murdersnake_sample_client_production
  <<: *development
